apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: add-task-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: dev-add-task-api.devsecopsguide.online
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: add-task
            port:
              number: 80
